FROM centos

MAINTAINER noriyuki020101 <noriyuki020101@gmail.com>

RUN yum -y update
RUN yum -y install https://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
RUN yum -y install rabbitmq-server

EXPOSE 15672
